objects/Sales_Bonus__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Sales Bonuses</relationshipLabel>
        <relationshipName>Sales_Bonuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unique_Key__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Unique Key</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Bonuses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Bonus</label>
    <nameField>
        <displayFormat>SB-{0000}</displayFormat>
        <label>Sales Bonus Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Bonuses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sales_Bonus_Rule__mdt.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Amount_Field__c</fullName>
        <label>Amount Field</label>
        <metadataRelationshipControllingField>Sales_Bonus_Rule__mdt.Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>Sales_Bonus_Rules</relationshipLabel>
        <relationshipName>Sales_Bonus_Rules</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Date_Field__c</fullName>
        <label>Date Field</label>
        <metadataRelationshipControllingField>Sales_Bonus_Rule__mdt.Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>Sales_Bonus_Rules2</relationshipLabel>
        <relationshipName>Sales_Bonus_Rules2</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <metadataRelationshipControllingField>Sales_Bonus_Rule__mdt.Object__c</metadataRelationshipControllingField>
        <referenceTo>FieldDefinition</referenceTo>
        <relationshipLabel>Sales_Bonus_Rules1</relationshipLabel>
        <relationshipName>Sales_Bonus_Rules1</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Sales Bonus Rule</label>
    <pluralLabel>Sales Bonus Rules</pluralLabel>
</CustomObject>

objects/User.object
<CustomObject>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
</CustomObject>

classes/SalesBonusService.cls
public without sharing class SalesBonusService {

    //delete [SELECT Id FROM Sales_Bonus__c];
    //SalesBonusService.updateBonuses();

    public static void updateBonuses() {

        //get all the CMDT rules
        List<Sales_Bonus_Rule__mdt> rules = [
            SELECT Id, Description__c, Start_Date__c, End_Date__c,
            Amount_Field__r.QualifiedApiName, User__r.QualifiedApiName, Date_Field__r.QualifiedApiName
            FROM Sales_Bonus_Rule__mdt
            WHERE Active__c = true
        ];

        //distinct sets of amount, user, date fields from CMDT so we can query later
        Set<String> amountFields = new Set<String>();
        Set<String> userFields = new Set<String>();
        Set<String> dateFields = new Set<String>();

        for (Sales_Bonus_Rule__mdt rule: rules) {
            amountFields.add(rule.Amount_Field__r.QualifiedApiName);
            userFields.add(rule.User__r.QualifiedApiName);
            dateFields.add(rule.Date_Field__r.QualifiedApiName);
        }

        //build a dynamic query of the fields from Opportunity which were references in the CMDT
        Set<String> allFields = new Set<String>();
        allFields.add('Id');
        allFields.addAll(amountFields);
        allFields.addAll(userFields);
        allFields.addAll(dateFields);
        String sFields = String.join(new List<String>(allFields), ',');
        String query = 'SELECT ' + sFields + ' FROM Opportunity';
        List<Opportunity> opps = Database.query(query);

        //empty list of bonuses to upsert
        List<Sales_Bonus__c> bonuses = new List<Sales_Bonus__c>();

        //apply all the rules too all the opps
        for (Opportunity opp: opps) {
            for (Sales_Bonus_Rule__mdt rule: rules) {
                Decimal amount = (Decimal)opp.get(rule.Amount_Field__r.QualifiedApiName);
                Date effectiveDate = (Date)opp.get(rule.Date_Field__r.QualifiedApiName);

                if ( amount == null || amount == 0 || (!isDateActive(rule, effectiveDate)) ) {
                    continue;
                }

                bonuses.add(new Sales_Bonus__c(
                    Amount__c = amount,
                    User__c = (Id)opp.get(rule.User__r.QualifiedApiName),
                    Effective_Date__c = effectiveDate,
                    Description__c = rule.Description__c,
                    Opportunity__c = opp.Id,
                    Unique_Key__c = opp.Id + '|' + rule.Id
                ));
            }
        }

        upsert bonuses Unique_Key__c;
    }

    private static Boolean isDateActive(Sales_Bonus_Rule__mdt rule, Date effectiveDate) {
        Boolean isActive = false;

        Boolean isAfterStart = (rule.Start_Date__c == null || effectiveDate >= rule.Start_Date__c);
        Boolean isBeforeEnd  = (rule.End_Date__c == null   || effectiveDate <= rule.End_Date__c);

        if (isAfterStart && isBeforeEnd) {
            isActive = true;
        }

        return isActive;
    }


}